City-of-Helsinki/liikunta-helsinki

- next.config.js
- package.json
- src/components/layout/Layout.tsx
- src/components/layout/getLayoutData.ts
- src/components/layout/layout.module.scss
- src/components/layout/tmp/menuItems.ts
- src/components/layout/types.ts
- src/components/meta/AppMeta.tsx
- src/components/meta/PageMeta.tsx
- src/components/navigation/Navigation.tsx
- src/components/navigation/navigation.module.scss
- src/components/page/Page.tsx
- src/components/page/getPageData.ts
- src/pages/_app.tsx
- src/pages/index.tsx
- src/styles/breakpoints.scss
- src/styles/fonts.scss
- src/styles/globals.scss
- src/styles/variables.scss
- src/types.ts
- yarn.lock
Adds top navigation to the application.
After this PR the application's landing page will render with a top navigation.
Some configurations were done to enable the navigation:
- HDS was added
- Helsinki Grotesk was added
- Layout logic was added
- Sass was added
- Meta data was added
In order to avoid implementing a too naive menu, I added mock data fetching logic for menu items.
This is sort of a problematic case with NextJS as currently there is no global, or app wide data fetching. See here: https://github.com/vercel/next.js/discussions/10949
Instead "global" data must be fetched view-by-view. This has the downside of creating duplicate code. I've implemented an initial approach for facilitating the fetching of menu data on each page.
> LIIKUNTA-31 | Add top navigation

- src/components/card/Card.tsx
- src/components/card/card.module.scss
- src/components/keyword/Keyword.tsx
- src/components/keyword/keyword.module.scss
- src/components/layout/Layout.tsx
- src/components/layout/layout.module.scss
- src/components/list/List.tsx
- src/components/list/list.module.scss
- src/components/section/Section.tsx
- src/components/section/section.module.scss
- src/components/text/Text.tsx
- src/components/text/text.module.scss
- src/pages/index.tsx
- src/tests/index.test.tsx
- src/types.ts
Adds a mock "popular no" section.
Takes inspiration and copies code from Tapahtumat.
I used an approach with the cards where they are not wrapped in an interactive element such as a link to make them easier to use with screen readers. However, I implemented some special logic for mouse users which allows them to click anywhere on the card to fire the navigation routine.
I also implemented the "call to action" (the arrow button) in a way where it's not focusable and as such does not introduce extra focusable elements, but does still communicate it's presence to sighted screen reader users (niche uscases).
I adopted a MVVM pattern with the card for now. I'll develop the approach further while implementing collections.
I could not find recommendations from WP so I was not able to mimic the …
> LIIKUNTA-58 | Add popular now section

- src/components/footer/Footer.tsx
- src/components/footer/footer.module.scss
- src/components/layout/Layout.tsx
- src/components/section/section.module.scss
Added HDS footer with a few tweaks:
* utility links are aligned to right side, normally they would go to left side when there are no SoMe items
* "back to top" button's slight vertical positioning error fixed
There is a known issue that the koros element inside the footer causes a warning about IDs not matching in server and client, but it shouldn't cause any real harm, and seems to be hard to fix, so it can be addressed later.
> LIIKUNTA-54 | Add footer from HDS

- src/api/LiikuntaApolloClient.ts
- src/api/cmsApolloClient.ts
- src/api/tmp/menuItems.ts
- src/api/utils.ts
- src/components/page/Page.tsx
- src/tests/index.test.tsx
In preparation for LIIKUNTA-29, simplify `pageQuery` logic and declare `RootQuery` as a query type in order to allow Apollo's cache to be built correctly.
> LIIKUNTA-29 | Fetch page data in a separate query

- src/api/utils.ts
- src/components/search/searchPageSearchForm/SearchPageSearchForm.tsx
- src/components/search/searchPageSearchForm/searchPageSearchForm.module.scss
- src/components/suggestionInput/SuggestionInput.tsx
- src/components/suggestionInput/suggestionInput.module.scss
Now while the user types, the UI should offer suggestions for the user. The suggestions should be in the currently chosen language.
The Combobox in HDS doesn't support our usecase. The combobox is designed for selecting one option from many. Our usecase is a text field that allows the user to optionally choose from a curated option list. The technical detail that makes it impossible to use Combobox is that it doesn't allow us to control the value of the input, which is why we are not able to track the value of the input--and hence make searches with it.
I implemented a custom dropdown which uses the same tooling as HDS does for its dropdown implementation.
The implementation lends more from HDS than from the implementation in events.
I added a very basic debouncing measure. This should …
> LIIKUNTA-63 | Add suggestion to free text search

- src/pages/index.tsx
So that the application can be tested appropriately.
Samuel and Päivi are planning a demo for the CMS/UI and this duplication makes the demo more difficult to do.
> Remove collection duplication

- src/pages/index.tsx
- src/pages/search/index.tsx
Revalidation had been accidentally declared within the props.
This meant that pages would never be re-built.
This would result in build time data always being used.
> Fix revalidation configuration for ISR

- src/pages/_app.tsx
- src/pages/_document.tsx
I tried my hardest to avoid creating a custom server. A custom server would remove some Next features and optimizations.
I was able to find this approach where we create a fake document and then attempt to reset it between requests.
This is a bandaid fix in that the document is not created per request. I wasn't able to find a better way to hook into the application logic early enough.
The ideal fix would be to add SSR support into HDS.
> LIIKUNTA-64 | Fix FOUC with statically optimized pages

- src/components/card/Card.tsx
- src/components/card/CondensedCard.tsx
- src/components/card/condensedCard.module.scss
- src/components/layout/layout.module.scss
- src/components/list/List.tsx
- src/components/list/list.module.scss
- src/components/section/Section.tsx
- src/components/section/section.module.scss
- src/pages/entities/[id].tsx
- src/styles/utils.scss
- src/tests/TestProviders.tsx
- src/tests/entities/[id].test.jsx
- src/tests/index.test.tsx
- src/tests/utils.tsx
I was able to use columns for this layout after all. The trick was to use `display: inline-block` on the element that appear as a child of the column container.
I also tried to use `flex`, but it would have required a fixed height to be set, which would have made reusability very difficult to do.
I implemented a new card type in order to comply with the desing.
> Liikunta 75 | Add upcoming events section

- .env.local.example
- .env.test
- .github/workflows/CI.yml
- .github/workflows/production.yml
- .github/workflows/review.yml
- .github/workflows/staging.yml
- src/client/cmsApolloClient.ts
- src/pages/index.tsx
- src/tests/index.test.tsx
- src/tests/mockData/landingPage.ts
The Graphql CMS API was updated and it broke our integration.
The `dekstopImage` query for landing page does not return the image I expected. I've sent a question about this to Geniem.
> Fix CMS integration

- src/pages/index.tsx
- src/tests/index.test.tsx
- src/types.ts
Don't fetch collections from the connection resolver, instead fetch collections that have been selected to be shown on the front page.
> Fetch collections from root page

- src/pages/search/index.tsx
Instead of searching from all locations, search from location which are marked to be under liikunta's "jurisdiction".
In this PR we take into use the `ontologyTreeId` filter and use it to target liikunta locations.
The three looks something like this:
```
KuVa
- One
- Two
- Liikunta (id: 551)
```
> LIIKUNTA-92 | Limit search results to sports locations

- src/domain/graphql/dataSources/Hauki.ts
- src/domain/graphql/dataSources/Linked.ts
- src/domain/graphql/dataSources/Tprek.ts
- src/domain/i18nRouter/useRouter.ts
- src/domain/i18nRouter/utils.ts
- src/util/events/getEventsAsItems.ts
- src/util/time/humanizeOpeningHoursForWeek.ts
In this PR I fix small bugs or slightly adjust behaviour based on comments.
**Fix datasources that assume a response object instead of respond data**  
When refactoring into using Apollo's DataSource class, the return type of the `get` method changed from an axios response to the data field within that response. This change fixes the incorrect assumption that a response object is returned.
This fixes issues with "ontologies" and opening hours.
**Don't treat empty hours as closed**  
When times were missing for dates and dates were grouped, those times were treated as closed. They should not have been treated as closed, instead they should have been treated as unknown. If times are missing, opening hours for that date are not shown.
* Fix `asPath` missing query when using the i18n friendly …
> Fix small bugs

- src/components/list/List.tsx
- src/components/list/list.module.scss
- src/widgets/upcomingEventsSection/UpcomingEventsSection.tsx
Use a grid instead of columns to get a left-to-right order instead of a column order for upcoming events.
> Use a grid instead of columns for upcoming events

- src/components/search/searchPageSearchForm/SearchPageSearchForm.tsx
- src/domain/unifiedSearch/useSearchParameters.ts
- src/domain/unifiedSearch/useSearchQuery.ts
Previously the search term would not reset on language change. This change forces the value to synchronise with search parameter values. The approach is not ideal, but I would not think of another small fix to resolve the issue.
> LIIKUNTA-124 | Fix search term not resetting in the UI

- i18nRoutes.config.js
- src/components/search/searchPageSearchForm/SearchPageSearchForm.tsx
- src/hooks/useSearch.ts
- src/pages/search/map.tsx
Previously searches in the map view of search would redirect the user into the search view. After this change map view searches will stick to the map view.
> LIIKUNTA-126 | Fix map searches redirecting to list view

- public/locales/en/search_page.json
- public/locales/fi/search_page.json
- public/locales/sv/search_page.json
- src/components/card/searchResultCard.module.scss
- src/domain/seo/meta/PageMeta.tsx
- src/domain/unifiedSearch/unifiedSearchResultVenueFragment.ts
- src/pages/search/index.tsx
- src/types.ts
- src/util/time/humanizeOpeningHoursForWeek.ts
Integrates into the new feature in US that allows for searching for the opening hours for the ongoing day.
Renders the opening hour for the ongoing day in the search results.
> LIIKUNTA-136 | Show opening hour for today in search results

- src/components/search/searchPageSearchForm/SearchPageSearchForm.tsx
If search was executed without selecting administrative division its value would be passed to unified search as undefined resulting to error.  Added a simple check that `administrativeDivisionId` is only passed to search if its selected.
> LIIKUNTA-130 | Fix administrativeDivisionId being passed as undefined

- src/components/layout/Layout.tsx
- src/components/layout/types.ts
- src/components/page/Page.tsx
- src/pages/search/map.tsx
Added a prop to `Page` component that hides the footer. Passing a prop through one extra component might not be ideal but imo it's clearer than adding a direct check to `Layout` component that checks if the url path matches the map view.
> LIIKUNTA-119 | Hide footer on map view

- src/domain/pagination/usePagination.tsx
- src/pages/collections/[slug].tsx
The load more announcer element was positioned unexpectedly which caused unexpected scroll behaviour.
Because the announcer element was absolutely positioned within the grid, its position on the page was outside the event list itself:
(Highlighted line is position of the announcer element)
I used the `preventScroll` option of the focus method to prevent scrolling on focus. Evergreen browsers should have support for it.
> LIIKUNTA-118 | Fix wrong scroll position when more events are loaded

- src/pages/search/index.tsx
Adds a few more checks to the "is open now" utility.
If start or end time is missing, the utility will not attempt to check the interval.
Added some logic for handling both the "closed" resource state and "fullDay" flag which were ignored previously.
> LIIKUNTA-143 | Make isOpenNow check more resistant to diverse times

- src/components/footer/Footer.tsx
- src/components/footer/footer.module.scss
Categories are removed from the footer.
Old version can be found from version control if they are introduced back at some point.
> LIIKUNTA-31 | Remove categories from the footer

- src/domain/events/upcomingEventsSection/UpcomingEventsSection.tsx
- src/domain/graphql/event/eventSchema.ts
- src/domain/graphql/services/linked/LinkedDataSource.ts
- src/pages/venues/[id].tsx
Adds keyword parameter to `linked events` events query. 
Testing:
1) [Review](https://liikunta-helsinki-67.test.kuva.hel.ninja/paikat/tprek:239)
2) [Staging](https://liikunta-helsinki.test.kuva.hel.ninja/paikat/tprek:239)
Seems that the keyword is filtering at least some events, in the testing case "Karanneet eläimet" event should not be shown in the Review environment.
> LIIKUNTA-125 | Add keyword parameter to events query.

- src/common/apollo/utils.ts
- src/domain/unifiedSearch/searchApolloClient.ts
- src/domain/unifiedSearch/tests/UnifiedSearch.test.js
- src/domain/unifiedSearch/useUnifiedSearch.ts
- src/domain/unifiedSearch/useUnifiedSearchQuery.ts
- src/pages/search/index.tsx
When clicking load more button in the search page, it causes page to scroll to top and then right back to load more announcer. Also same request is done twice to API when fetching more event with load more button, I think it has something to do with `router.replace` and useQuerys fetchPolicy settings. To fix this issue, I added possibility to add `TransitionOptions` to setFilters function. Also unifiedSearchQuery wasn't using variables for caching because of `relayStylePagination`. I think we can get better cahcing by using keyArgs and getting rid of non-default fetching policies.
- Added possibility to pass TransitionOptions to setFilters function
- Deleted fetch policies from useUnifiedSearchQuery apollo hook 
- Added `excludeArgs` utility to be used with `relayStylePagination`
Click …
> Fix scrolling issue when loading more events

- src/common/components/footer/footer.module.scss
Footer had extra line between koros and solid bottom area.
LIIKUNTA-182
> Fix footer koros style

- src/common/components/list/SearchList.tsx
More result announcer wasn't focused to correct place when loading less than 10 (block size) more venues. Also `loadedMoreAmount` was incorrect (0) when loading less than 10 results.
**[LIIKUNTA-183](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-183):**
> LIIKUNTA-183 | Fix a11yIndex calculation when loading more results

- public/locales/en/footer.json
- public/locales/fi/footer.json
- public/locales/sv/footer.json
- src/common/components/footer/Footer.tsx
Removed the 2nd line from footer, since we don’t have the feedback feature yet (so the link does not do anything) and “backToTopLabel“ -feature is hard-coded to be in Footer-utilities by HDS. The middle row does not have any tests either. The second row just looked empty and funny as is also described in the Jira ticket.
LIIKUNTA-193
HDS Footer specs: https://hds.hel.fi/components/footer#default
NOTE: This PR is into https://github.com/City-of-Helsinki/liikunta-helsinki/tree/LIIKUNTA-182-fix-koros, since it has fixes to koros.
> Removed the HDS utility row from footer

- next.config.js
- src/common/components/dateTimePicker/DateTimePicker.tsx
- src/common/components/dateTimePicker/dateTimePicker.module.scss
- src/common/components/keyword/Keyword.tsx
- src/domain/search/searchPageSearchForm/SearchPageSearchForm.tsx
- src/pages/search/index.tsx
The main change here is that we are dropping pagination parameters from the search and hence not persisting them over page refreshes. This results in behaviour where on page refreshes, instead of the last page, the first page is shown.
This PR also contains a few other very minor fixes:
- Adjusts font-size and color for DateTimePicker's button component so that it's inline with HDS
- Adds experimental `scrollRestoration: true` config to NextJS which should fix unrestored scroll state on `history.back`. Mainly affected us on the search view.
- Integrates the filter list with query persister, fixing issue where queries modified through the filter list would not be persisted
> LIIKUNTA-195 | On search results refresh, show first page instead of last

- src/domain/i18n/router/Link.tsx
- src/domain/i18n/router/__test__/Link.test.js
- src/domain/i18n/router/__test__/utils.test.js
- src/domain/i18n/router/utils.ts
- src/domain/search/searchPageSearchForm/SearchPageSearchForm.tsx
The issues were caused by behaviour that differs from the default behaviour of NextJS and were brought about with the change where we begun to use our custom stringification routine by default. Unfortunately it didn't have support for `query` as a way of providing search parameters, nor did it retain the current `pathname` if a new one was not provided. The stringification routine Next uses is relatively complex and this regression highlights the difficulty of maintaining logic that attempts to mimic that. We should look to replace the current `escape` with a better approach, but I didn't spend time on that now.
> LIIKUNTA-210 | Fix broken filter keywords

- src/common/components/list/SearchList.tsx
- src/common/components/mapView/mapConstants.ts
- src/domain/search/landingPageSearchForm/LandingPageSearchForm.tsx
- src/domain/search/searchPageSearchForm/SearchPageSearchForm.tsx
- src/domain/unifiedSearch/types.ts
- src/domain/unifiedSearch/unifiedSearchConstants.ts
- src/domain/unifiedSearch/useUnifiedSearchQuery.ts
- src/pages/search/index.tsx
- src/pages/search/map.tsx
Changes the default sort order to alphabetical (by name).
When user completes a search, the search order should be set to relevance. Ordering by relevance after there are search criteria will likely makes more sense.
I've extended the sort controls to contain all sort criteria to simplify the code and UX.
Changes map default center based on the design in the linked task.
**[LIIKUNTA-188](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-188)**
**[LIIKUNTA-188](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-188)**
> LIIKUNTA 188, 196 | Adjust map center and default sort order

- src/pages/venues/[id]/map/index.tsx
- Use venue id from query to fix issues with unsupported venue data sources
**[LIIKUNTA-213](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-213):**
> fix broken venue ids in venue map page

- src/common/components/hero/Hero.tsx
- src/common/components/hero/hero.module.scss
- src/common/components/hero/heroImage.module.scss
- src/domain/search/landingPageSearchForm/landingPageSearchForm.module.scss
- src/domain/search/searchPageSearchForm/SearchPageSearchForm.tsx
- src/domain/search/searchPageSearchForm/searchPageSearchForm.module.scss
Adjust sizes of elements before the fold so that more content can be shown to the use with screen sizes of `1280x720`.
The designer who requested this change has checked it initially and given a thumbs up.
**[LIIKUNTA-206](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-206):**
> LIIKUNTA-206 | Fit more content before the fold on landing and search page

- src/domain/search/landingPageSearchForm/LandingPageSearchForm.tsx
- src/domain/search/searchPageSearchForm/SearchPageSearchForm.tsx
Fixes issue where a search with empty filters would change `orderBy` into `relevance`. After this change, only searches with filters should change `orderBy` into `relevance`.
**[LIIKUNTA-196](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-196)**
> LIIKUNTA-196 | Order by name when filters are empty

- src/domain/unifiedSearch/useUnifiedSearchListQuery.ts
- src/domain/unifiedSearch/venuesByOntologyWords/VenuesByOntologyWords.tsx
- src/domain/venues/utils/__tests__/getVenueIdParts.ts
- src/domain/venues/utils/getVenueIdParts.ts
- src/domain/venues/utils/getVenuesAsItems.ts
- src/pages/venues/[id]/index.tsx
Previously the id from `tprek` was used as is. The id also contained its source (for instance `lipas:...`) which caused the site to build an incorrect link.
After this change the source information is ignored and it's replaced with `tprek`.
Contains a slight refactor for how parts of a venue id are parsed.
**[LIIKUNTA-158](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-158)**
This collections contains a venue selection: http://localhost:3000/kokoelmat/meno-ja-meininkia-viikonlopuksi
> FIX LIIKUNTA-158 | Fix location selection links

- src/common/components/dateTimePicker/dateTimePicker.module.scss
- src/domain/venues/utils/getVenuesAsItems.ts
- yarn.lock
Changes z-index so that date time picker isn't rendered below keywords.
**[LIIKUNTA-259](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-259):**
> LIIKUNTA-259 | Fix ontologies overlapping datetime picker

- src/pages/venues/[id]/index.tsx
- src/tests/venues/[id].test.jsx
Show initially 4 of price information in location page
**[LIIKUNTA-268](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-268):**
> LIIKUNTA-268 | Show initially 4 of price information in location page

- src/common/components/card/CondensedCard.tsx
- src/common/components/dateTimePicker/DateTimePicker.tsx
- src/common/geolocation/GeolocationProvider.tsx
- src/common/utils/sendToast.tsx
- src/pages/venues/[id]/map/index.tsx
Always imports `useTranslation` from `next-i18next` so that the hooks has the correct translation context.
> Always import useTranslation from next-i18next

- .eslintrc.json
- src/domain/clients/cmsApolloClient.ts
- src/domain/clients/nextApiApolloClient.ts
- src/pages/venues/[id]/index.tsx
- src/pages/venues/[id]/map/index.tsx
Changing language didn't change the language of venue's fields on the venue page. Main issue was that we were using same apollo client in server side between requests. I think new apollo client with empty cache should be created with every revalidation. Now we can still use `Accept-Language` header to request different languages.
**[LIIKUNTA-269](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-269):**
> LIIKUNTA-269 | Fix language changing problem in venue page

- public/locales/en/card.json
- public/locales/en/common.json
- public/locales/en/geolocation_provider.json
- public/locales/en/hardcoded_shortcuts.json
- public/locales/en/map_box.json
- public/locales/en/navigation.json
- public/locales/en/search_header.json
- public/locales/en/search_list.json
- public/locales/en/search_page.json
- public/locales/en/search_page_search_form.json
- public/locales/en/utils.json
- public/locales/en/venue_page.json
- public/locales/sv/card.json
- public/locales/sv/common.json
- public/locales/sv/geolocation_provider.json
- public/locales/sv/hardcoded_shortcuts.json
- public/locales/sv/map_box.json
- public/locales/sv/navigation.json
- public/locales/sv/search_header.json
- public/locales/sv/search_list.json
- public/locales/sv/search_page.json
- public/locales/sv/search_page_search_form.json
- public/locales/sv/utils.json
- public/locales/sv/venue_page.json
I've updated the missing translations into the CMS and fetched them into the source code.
I checked that there were no untranslated strings in the application currently by searching over the translations for `EN` and `SV`
**[LIIKUNTA-264](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-264)**
> LIIKUNTA-264 | Add missing translations

- public/locales/en/common.json
- public/locales/en/footer.json
- public/locales/en/info_block.json
- public/locales/en/map_box.json
- public/locales/fi/common.json
- public/locales/fi/footer.json
- public/locales/fi/info_block.json
- public/locales/fi/map_box.json
- public/locales/fi/upcoming_events_section.json
- public/locales/sv/common.json
- public/locales/sv/footer.json
- public/locales/sv/info_block.json
- public/locales/sv/map_box.json
- src/common/components/footer/Footer.tsx
- src/common/components/footer/footer.module.scss
- src/common/components/infoBlock/InfoBlock.tsx
- src/domain/i18n/serverSideTranslationsWithCommon.ts
- src/tests/initI18n.ts
- Add feedback link to footer (move "opens in a new tab" translation to common)
- Fix spelling mistake in venue pages "Next events" finnish title
**[LIIKUNTA-272](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-272):**
**[LIIKUNTA-273](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-273):**
> LIIKUNTA-272, LIIKUNTA-273 | Add feedback link to footer and fix spelling mistake in venue page

- .github/workflows/production.yml
- CHANGELOG.md
- README.md
Problem was that https://liikunta-helsinki.prod.kuva.hel.ninja didn't allow request from the new public facing production domain.
Fix here is to make the request into an endpoint in the same origin so that the browser doesn't complain about CORS.
Configures the instance in the production environment to work with the public facing domain name. After this change, the version with the private domain name will not work.
This is somewhat quick and dirty.
Other fixes:
- Disable CORS (https://github.com/vercel/next.js/tree/canary/examples/api-routes-cors)
- Allow both production domains (https://stackoverflow.com/a/59600058)
**[LIIKUNTA-286](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-286):**
> LIIKUNTA-286 | Fix instance for public facing production domain

- src/common/components/card/Card.tsx
- src/common/components/card/LargeCollectionCard.tsx
- src/common/components/card/card.module.scss
- src/common/utils/formatToSingleTag.ts
- src/common/utils/tests/formatToSingleTag.test.js
- src/types.ts
Css fix for the frontpage large card to limit the number of lines to show
> HL-274: Large card line limit 3

- public/locales/en/venue_page.json
- public/locales/fi/venue_page.json
- public/locales/sv/venue_page.json
- src/__tests__/venues/__mocks__/[id].tsx
- src/domain/graphql/__tests__/__snapshots__/graphqlEndpointIntegration.test.js.snap
- src/domain/graphql/__tests__/graphqlEndpointIntegration.test.js
- src/domain/graphql/venue/instructions/VenueTprekIntegration.ts
- src/domain/graphql/venue/venueSchema.ts
- src/pages/venues/[id]/index.tsx
- src/types.ts
The contact information of the venue moved from Other details section to separate Contact information section. The contact information is extended with connections contact details data
> LIIKUNTA-267: Add contact information from connections

- src/common/components/card/card.module.scss
Fix for keywords overlapping the dropdown values.
> LIIKUNTA-287: Card keywords z-index fix

- src/common/components/card/card.module.scss
- src/common/components/hero/hero.module.scss
- src/common/components/list/list.module.scss
Previously the content of the index page would overflow its container on small screens.
After this change, elements have been adjusted so that they can be scaled on small screens.
You should see scroll bras on staging when using a screen size of 320px. Those scroll bars should be missing in this PR.
Reproducing the issue wit Chrome was difficult. It was easier to do with for instance Safari.
On Chrome you need to set the viewport to 320, click within the viewport, zoom with ctrl+ and the reset zoom with ctrl+0.
**[LIIKUNTA-282](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-282)**
> LIIKUNTA-282 | Fix viewport overflow issues on small mobile screens

- src/common/components/list/list.module.scss
The previous fix broke lists on bigger screen.
This alternative fix decreases grid minimum cell width on small screens so that lists can fit 320px screen sizes.
**[LIIKUNTA-282](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-282)**
> LIIKUNTA-282 | Fix list grids on bigger screen sizes

- CHANGELOG.md
- package.json
- Missing images on collection page for venue selections
- A11y: When advising about external links, or links that open in a new tab, include the info text by using aria-label
- A11y: Page scales for window size with the width of 320px
- Keyword overflow on search page
- Social links under other details on single location page
- Location section from single location page sidebar
- Let app know about its origin instead of its graphql endpoint
- Separate 'contact information' and 'other info' sections in single location page sidebar
- Limit collection description text to maximum of three rows
- Increase size of collection description text
> Document release 1.1.0

- .github/workflows/production.yml
- .github/workflows/review.yml
- .github/workflows/staging.yml
https://helsinkicity.slack.com/archives/C01DWA87NJC/p1651312291390169
> @channel liikuntahelsinki on hakannut juuri vaihtuneen Sentryn laskutuskauden koko 100k eventin quotan täyteen päivässä - katsokaa mikä pissii
https://docs.sentry.io/platforms/javascript/configuration/sampling/
> Disable the Sentry transactions tracing
