City-of-Helsinki/liikunta-helsinki

- src/components/hero/Hero.tsx
- src/components/hero/hero.module.scss
- src/components/list/List.tsx
- src/pages/index.tsx
- src/tests/index.test.tsx
- src/types.ts
Added the hero section. The LandingPage type might change later, depending on how we will end up fetching the data.
> LIIKUNTA-55 | Add hero section

- .env.local.example
- .env.test
- .github/workflows/CI.yml
- .github/workflows/production.yml
- .github/workflows/review.yml
- .github/workflows/staging.yml
- Dockerfile
- src/api/searchApolloClient.ts
- src/components/card/searchResultCard.module.scss
- src/components/card/searchResultCard.tsx
- src/components/list/List.tsx
- src/components/list/list.module.scss
- src/components/search/searchPageSearchForm/SearchPageSearchForm.tsx
- src/components/text/Text.tsx
- src/config.ts
- src/pages/search/index.tsx
- src/pages/search/search.module.scss
- src/types.ts
Implemented initial search functionality using the [Unified Search.](https://github.com/City-of-Helsinki/unified-search)
There is currently only free text search for locations available, and the amount of information provided about those is also very limited.
The layout for displaying search results is also very initial and just there to get some visible results, and will need lots of love once we know what kind of info exactly needs to be there.
> LIIKUNTA-61 | Unified search integration

- src/components/navigation/Navigation.tsx
Just a couple of small navigation bar logo related functionalities. Implemented now because an older developer got mad at clicking the logo was not working.
> Navigation bar logo functionality enhancements

- src/components/footer/Footer.tsx
- src/components/footer/footer.module.scss
- src/components/link/categoryLink.module.scss
- src/components/searchShortcuts/SearchShortcuts.tsx
- src/pages/index.tsx
Adds the same shortcuts that are shown under the search bar into the footer.
> LIIKUNTA-25 | Add search shortcuts to footer

- src/components/layout/layout.module.scss
- src/components/list/list.module.scss
- src/styles/breakpoints.scss
Increased margin used on desktop width.
> Chore | Increase layout margin on desktop width.

- src/client/cmsApolloClient.ts
- src/client/initializeApolloClient.ts
- src/client/nextApiApolloClient.ts
Previously language changing would not work in the venue page.
After this change data should update when language is changed.
> Fix language changing on venue page

- src/pages/search/index.tsx
- src/pages/venues/[id].tsx
- src/types.ts
- src/util/capitalize.ts
> LIIKUNTA-97 | Use real keywords in search result list

- src/components/infoTemplate/InfoTemplate.tsx
- src/components/infoTemplate/infoTemplate.module.scss
- src/components/list/SearchList.tsx
Adds an empty search notice when there are no results for a search.
> LIIKUNTA-69 | Add no results message

- src/client/apolloErrorLink.ts
- src/client/searchApolloClient.ts
- src/components/combobox/Combobox.tsx
- src/components/combobox/combobox.module.scss
- src/components/mapView/MapView.tsx
- src/components/search/searchHeader/searchHeader.module.scss
- src/components/search/searchPageSearchForm/SearchPageSearchForm.tsx
- src/components/search/searchPageSearchForm/searchPageSearchForm.module.scss
- src/components/select/Select.tsx
- src/components/select/select.module.scss
- src/components/suggestionInput/suggestionInput.module.scss
- src/domain/i18nRouter/useRouter.ts
- src/domain/logger.ts
- src/domain/unifiedSearch/unifiedSearchResultVenueFragment.ts
- src/domain/unifiedSearch/useSearchParameters.ts
- src/domain/unifiedSearch/useSearchQuery.ts
- src/hooks/useSearch.ts
- src/pages/search/index.tsx
- src/pages/search/map.tsx
- src/styles/utils.scss
- src/types.ts
- src/util/getTranslation.ts
- src/widgets/administrativeDivisionDropdown/AdministrativeDivisionDropdown.tsx
Once fetching for administrative divisions work, this change can be tested and merged.
> LIIKUNTA-18 | Add administrative division filter to search page

- public/locales/en/map_view.json
- public/locales/fi/map_view.json
- public/locales/sv/map_view.json
- src/components/mapView/MapView.tsx
- src/components/mapView/VenueIcon.ts
- src/components/mapView/mapView.module.scss
This PR makes map view is more accessible (or little less as keyboard navigation is disabled 😅 little confused here). Added a wrapper for MapContainer that should tell user that they have focused a map and it's meant for visual users only.
> LIIKUNTA-99 | Make map view more accessible.

- package.json
- src/components/mapView/MapView.tsx
- src/components/mapView/mapView.module.scss
- yarn.lock
POI that are close to each other on the map are now clustered. By clicking on the cluster, the map is zoomed. Clusters are also unclustered when the user zooms the map.
Also stops using fork of `react-leaflet` as the application now supports webpack 5.
> LIIKUNTA-138 | Add clustering to map view

- i18nRoutes.config.js
- src/components/footer/Footer.tsx
- src/components/htmlToReact/HtmlToReact.tsx
- src/components/section/Section.tsx
- src/components/section/section.module.scss
- src/pages/about/index.tsx
- src/pages/accessibility/index.tsx
This PR adds accessibility statement and about us pages. I'm still wondering if I should have created one component that eats `PAGE_QUERY` as the data is almost identical between the pages 🤔.
> LIKUNTA-115 | Add accessibility statement and about us pages

- src/common/components/mapView/A11yHiddenIcon.ts
- src/common/components/mapView/MapView.tsx
- src/common/components/mapView/VenueIcon.ts
Hides the cluster icon from screen readers.
> Hide cluster icon from screen readers

- src/domain/unifiedSearch/administrativeDivisionDropdown/useAdministrativeDivisions.ts
[These.](https://github.com/City-of-Helsinki/unified-search/pull/54)
> LIIKUNTA-155 | Use "Helsinki common administrative divisions"

- docker-compose.yml
Fixed docker-compose environment by adding .env.local as a env configuration.
LIIKUNTA-180
> Added .env.local as an environment for docker-compose configuration

- src/common/components/mapView/MapView.tsx
Venues that are clustered on max zoom did not previously open their popup when they were focused.
This change invokes `zoomToShowLayer` before opening the popup, which "unravels" (spiderifies) clustered markers, allowing for the popup invocation to open the popup.
**[LIIKUNTA-212](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-212)**
> LIIKUNTA-212 | Fix non visible popup when focusing clustered venue

- src/common/components/card/Card.tsx
- src/common/components/card/DefaultCard.tsx
- src/common/components/card/card.module.scss
- src/common/components/section/Section.tsx
- src/domain/events/searchEvents/SearchEvents.tsx
- src/domain/events/selectedEvents/SelectedEvents.tsx
- src/domain/events/upcomingEventsSection/UpcomingEventsSection.tsx
- src/domain/unifiedSearch/venuesByOntologyWords/VenuesByOntologyWords.tsx
- src/domain/venues/SelectedVenues.tsx
- src/pages/venues/[id]/index.tsx
- src/types.ts
Add section for showing other similar places.
**[LIIKUNTA-129](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-129):**
> LIIKUNTA-129 | Add recommended sport places on venue page

- package.json
Fixes issue in staging that causes next server to crash.
> Move runtime depedency into main deps

- src/pages/venues/[id]/venue.module.scss
Adjusted venue page layout to match design. Not sure if "Muuta samankailtaista liikuntaa" section would also need some adjustment.
**[LIIKUNTA-270](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-270):**
> LIIKUNTA-270 | Adjust venue grid layout ot match the design

- .github/workflows/production.yml
> Set production Unified-Search URL to production configuration

- sentry.server.config.js
> fix: sentry env check

- CHANGELOG.md
- package.json
- Configured production environment to work from https://liikunta.hel.fi
> Document release 1.0.0

- src/common/components/card/CollectionCard.tsx
- src/common/components/card/LargeCollectionCard.tsx
- src/common/components/htmlToReact/HtmlToReact.tsx
- src/pages/collections/[slug].tsx
-Fixed font sized and hline-heights for collection cards
> LIIKUNTA-275: Fonts

- src/common/components/card/CollectionCard.tsx
Add clamp as well to the collection cards
> LIIKUNTA-274: Fix collection cards clamp
